server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lql534/springcloud-config.git
          # 删除 search-paths 或改为 /
          search-paths: /
          skip-ssl-validation: true
          default-label: master
          username: lql
          password: lql050304
          timeout: 10
          force-pull: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

management:
  endpoints:
    web:
      exposure:
        include: '*'